### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by fulldecent** [ruanmartinelli/axist#3]
Please support nesting for ul/li.

```html
  <li>Top level
    <ul>
      <li>Inside</li>
    </ul>
  </li>
```

Current render:

<img width="180" alt="Screen Shot 2020-07-20 at 23 26 47" src="https://user-images.githubusercontent.com/382183/88009437-7e611c80-cae0-11ea-80a0-b721c38ad44a.png">

**Comment by ruanmartinelli** [comment]
Thanks for the heads up! I'll take a look 👍
